package com.ra.course.aws.online.shopping.dao;

import com.ra.course.aws.online.shopping.AwsOnlineShoppingApplication;
import com.ra.course.aws.online.shopping.TestConfig;
import com.ra.course.aws.online.shopping.entity.Address;
import com.ra.course.aws.online.shopping.entity.enums.AccountStatus;
import com.ra.course.aws.online.shopping.entity.payment.CreditCard;
import com.ra.course.aws.online.shopping.entity.payment.ElectronicBankTransfer;
import com.ra.course.aws.online.shopping.entity.user.Account;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(classes = {AwsOnlineShoppingApplication.class, TestConfig.class})
@ActiveProfiles("local")
@Sql(scripts = {"classpath:schema.sql", "classpath:test-data.sql"})
public class AddressDaoImplIntegrationTest {

    @Autowired
    private AddressDao addressDao;

    @Test
    @DisplayName("Should insert address into DB an return autogenerated ID")
    public void saveTest() {
        Address address = new Address("Garmatna", "Kyiv", "Kyiv", "01135", "Ukraine");
        Long expectedId = 4L;
        Long savedAccountId = addressDao.save(address);
        assertEquals(expectedId, savedAccountId);
    }

    @Test
    public void updateTest() {

    }

    @Test
    public void removeTest() {

    }

    @Test
    public void findByIDTest() {

    }
}

