package com.ra.course.aws.online.shopping.dao;

import com.ra.course.aws.online.shopping.AwsOnlineShoppingApplication;
import com.ra.course.aws.online.shopping.TestConfig;
import com.ra.course.aws.online.shopping.entity.Address;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(classes = {AwsOnlineShoppingApplication.class, TestConfig.class})
@ActiveProfiles("local")
@Sql(scripts = {"classpath:schema.sql", "classpath:test-data.sql"})
public class AddressDaoImplIntegrationTest {

    @Autowired
    private AddressDao addressDao;
    private Address address;

    @BeforeEach
    void setUp() {
        address = new Address("Garmatna", "Kyiv", "Kyiv", "01135", "Ukraine");
    }

    @Test
    @DisplayName("Should insert address into DB an return autogenerated ID")
    public void saveTest() {
        Long expectedId = 7L;
        Long savedAccountId = addressDao.save(address);
        assertEquals(expectedId, savedAccountId);
    }

    @Test
    public void updateTest() {
        address.setId(1L);
        assertTrue(addressDao.update(address));
    }

    @Test
    public void removeTest() {
        assertTrue(addressDao.remove(1L));
    }

    @Test
    public void findByIDTest() {
        Address address = addressDao.findById(1L);
        assertAll(() -> {
            assertEquals(address.getStreetAddress(), "Gonchara");
            assertEquals(address.getCity(), "Kyiv");
            assertEquals(address.getState(), "Kyiv");
            assertEquals(address.getZipCode(), "01134");
            assertEquals(address.getCountry(), "Ukraine");
            assertEquals(address.getId(), 1L);
        });
    }
}

