package com.ra.course.aws.online.shopping.dao;

import com.ra.course.aws.online.shopping.AwsOnlineShoppingApplication;
import com.ra.course.aws.online.shopping.TestConfig;
import com.ra.course.aws.online.shopping.entity.Address;
import com.ra.course.aws.online.shopping.entity.payment.CreditCard;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(classes = {AwsOnlineShoppingApplication.class, TestConfig.class})
@ActiveProfiles("test")
@Sql(scripts = {"classpath:schema.sql", "classpath:test-data.sql"})
public class CreditCardDaoImplIntegrationTest {

    @Autowired
    private CreditCardDao creditCardDao;
    @Autowired
    private AccountDao accountDao;

    @Test
    @DisplayName("Returned autogenerated credit card id should be equal to expected")
    @Rollback
    public void saveTest() {
        Long expectedId = 7L;
        Long accountId = 2L;

        Address address = new Address("Bohatyrska", "Lviv", "Lviv", "11111", "Ukraine");
        CreditCard card = new CreditCard("Roger", "5525694123698541", 145, address);

        Long cardId = (creditCardDao.save(accountId, card));
        assertEquals(expectedId, cardId);
    }

    @Test
    @Rollback
    public void removeTest() {
        assertTrue(creditCardDao.remove("000000"));
    }
}