spring:
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/aws_shopping
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5

