/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Indexes;
import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.MemberVotedCommentRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberVotedCommentTable extends TableImpl<MemberVotedCommentRecord> {

    private static final long serialVersionUID = 2101011576;

    /**
     * The reference instance of <code>public.member_voted_comment</code>
     */
    public static final MemberVotedCommentTable MEMBER_VOTED_COMMENT_TABLE = new MemberVotedCommentTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MemberVotedCommentRecord> getRecordType() {
        return MemberVotedCommentRecord.class;
    }

    /**
     * The column <code>public.member_voted_comment.account_id</code>.
     */
    public static final TableField<MemberVotedCommentRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEMBER_VOTED_COMMENT_TABLE, "");

    /**
     * The column <code>public.member_voted_comment.comment_id</code>.
     */
    public static final TableField<MemberVotedCommentRecord, Long> COMMENT_ID = createField(DSL.name("comment_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEMBER_VOTED_COMMENT_TABLE, "");

    /**
     * The column <code>public.member_voted_comment.upvoted</code>.
     */
    public static final TableField<MemberVotedCommentRecord, Boolean> UPVOTED = createField(DSL.name("upvoted"), org.jooq.impl.SQLDataType.BOOLEAN, MEMBER_VOTED_COMMENT_TABLE, "");

    /**
     * No further instances allowed
     */
    private MemberVotedCommentTable() {
        this(DSL.name("member_voted_comment"), null);
    }

    private MemberVotedCommentTable(Name alias, Table<MemberVotedCommentRecord> aliased) {
        this(alias, aliased, null);
    }

    private MemberVotedCommentTable(Name alias, Table<MemberVotedCommentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MemberVotedCommentTable(Table<O> child, ForeignKey<O, MemberVotedCommentRecord> key) {
        super(child, key, MEMBER_VOTED_COMMENT_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEMBER_VOTED_COMMENT_PKEY);
    }

    @Override
    public UniqueKey<MemberVotedCommentRecord> getPrimaryKey() {
        return Keys.MEMBER_VOTED_COMMENT_PKEY;
    }

    @Override
    public List<UniqueKey<MemberVotedCommentRecord>> getKeys() {
        return Arrays.<UniqueKey<MemberVotedCommentRecord>>asList(Keys.MEMBER_VOTED_COMMENT_PKEY);
    }

    @Override
    public List<ForeignKey<MemberVotedCommentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MemberVotedCommentRecord, ?>>asList(Keys.MEMBER_VOTED_COMMENT__FK_ACCOUNT_VOTED_COMMENT_ACCOUNT_ID, Keys.MEMBER_VOTED_COMMENT__FK_ACCOUNT_VOTED_COMMENT_COMMENT_ID);
    }

    public AccountTable account() {
        return new AccountTable(this, Keys.MEMBER_VOTED_COMMENT__FK_ACCOUNT_VOTED_COMMENT_ACCOUNT_ID);
    }

    public CommentTable comment() {
        return new CommentTable(this, Keys.MEMBER_VOTED_COMMENT__FK_ACCOUNT_VOTED_COMMENT_COMMENT_ID);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
