/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Indexes;
import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.enums.BadgeType;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.MemberBadgeQuestionRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberBadgeQuestionTable extends TableImpl<MemberBadgeQuestionRecord> {

    private static final long serialVersionUID = 474483404;

    /**
     * The reference instance of <code>public.member_badge_question</code>
     */
    public static final MemberBadgeQuestionTable MEMBER_BADGE_QUESTION_TABLE = new MemberBadgeQuestionTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MemberBadgeQuestionRecord> getRecordType() {
        return MemberBadgeQuestionRecord.class;
    }

    /**
     * The column <code>public.member_badge_question.account_id</code>.
     */
    public static final TableField<MemberBadgeQuestionRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEMBER_BADGE_QUESTION_TABLE, "");

    /**
     * The column <code>public.member_badge_question.badge</code>.
     */
    public static final TableField<MemberBadgeQuestionRecord, BadgeType> BADGE = createField(DSL.name("badge"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(com.ra.course.com.stackoverflow.entity.jooq.enums.BadgeType.class), MEMBER_BADGE_QUESTION_TABLE, "");

    /**
     * The column <code>public.member_badge_question.question_id</code>.
     */
    public static final TableField<MemberBadgeQuestionRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEMBER_BADGE_QUESTION_TABLE, "");

    /**
     * No further instances allowed
     */
    private MemberBadgeQuestionTable() {
        this(DSL.name("member_badge_question"), null);
    }

    private MemberBadgeQuestionTable(Name alias, Table<MemberBadgeQuestionRecord> aliased) {
        this(alias, aliased, null);
    }

    private MemberBadgeQuestionTable(Name alias, Table<MemberBadgeQuestionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MemberBadgeQuestionTable(Table<O> child, ForeignKey<O, MemberBadgeQuestionRecord> key) {
        super(child, key, MEMBER_BADGE_QUESTION_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEMBER_BADGE_QUESTION_PKEY);
    }

    @Override
    public UniqueKey<MemberBadgeQuestionRecord> getPrimaryKey() {
        return Keys.MEMBER_BADGE_QUESTION_PKEY;
    }

    @Override
    public List<UniqueKey<MemberBadgeQuestionRecord>> getKeys() {
        return Arrays.<UniqueKey<MemberBadgeQuestionRecord>>asList(Keys.MEMBER_BADGE_QUESTION_PKEY);
    }

    @Override
    public List<ForeignKey<MemberBadgeQuestionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MemberBadgeQuestionRecord, ?>>asList(Keys.MEMBER_BADGE_QUESTION__FK_ACCOUNT_BADGE_QUESTION_ACCOUNT_ID, Keys.MEMBER_BADGE_QUESTION__FK_ACCOUNT_BADGE_QUESTION_QUESTION_ID);
    }

    public AccountTable account() {
        return new AccountTable(this, Keys.MEMBER_BADGE_QUESTION__FK_ACCOUNT_BADGE_QUESTION_ACCOUNT_ID);
    }

    public QuestionTable question() {
        return new QuestionTable(this, Keys.MEMBER_BADGE_QUESTION__FK_ACCOUNT_BADGE_QUESTION_QUESTION_ID);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, BadgeType, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
