/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.MemberRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberTable extends TableImpl<MemberRecord> {

    private static final long serialVersionUID = 1228405885;

    /**
     * The reference instance of <code>public.member</code>
     */
    public static final MemberTable MEMBER_TABLE = new MemberTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MemberRecord> getRecordType() {
        return MemberRecord.class;
    }

    /**
     * The column <code>public.member.id</code>.
     */
    public final TableField<MemberRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('member_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.member.account_id</code>.
     */
    public final TableField<MemberRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.member</code> table reference
     */
    public MemberTable() {
        this(DSL.name("member"), null);
    }

    /**
     * Create an aliased <code>public.member</code> table reference
     */
    public MemberTable(String alias) {
        this(DSL.name(alias), MEMBER_TABLE);
    }

    /**
     * Create an aliased <code>public.member</code> table reference
     */
    public MemberTable(Name alias) {
        this(alias, MEMBER_TABLE);
    }

    private MemberTable(Name alias, Table<MemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private MemberTable(Name alias, Table<MemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> MemberTable(Table<O> child, ForeignKey<O, MemberRecord> key) {
        super(child, key, MEMBER_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<MemberRecord, Long> getIdentity() {
        return Keys.IDENTITY_MEMBER;
    }

    @Override
    public UniqueKey<MemberRecord> getPrimaryKey() {
        return Keys.MEMBER_PKEY;
    }

    @Override
    public List<UniqueKey<MemberRecord>> getKeys() {
        return Arrays.<UniqueKey<MemberRecord>>asList(Keys.MEMBER_PKEY);
    }

    @Override
    public List<ForeignKey<MemberRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MemberRecord, ?>>asList(Keys.MEMBER__FK_ACCOUNT_ID);
    }

    public AccountTable account() {
        return new AccountTable(this, Keys.MEMBER__FK_ACCOUNT_ID);
    }

    @Override
    public MemberTable as(String alias) {
        return new MemberTable(DSL.name(alias), this);
    }

    @Override
    public MemberTable as(Name alias) {
        return new MemberTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberTable rename(String name) {
        return new MemberTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberTable rename(Name name) {
        return new MemberTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
