/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Indexes;
import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.MemberVotedQuestionRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberVotedQuestionTable extends TableImpl<MemberVotedQuestionRecord> {

    private static final long serialVersionUID = 1489304967;

    /**
     * The reference instance of <code>public.member_voted_question</code>
     */
    public static final MemberVotedQuestionTable MEMBER_VOTED_QUESTION_TABLE = new MemberVotedQuestionTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MemberVotedQuestionRecord> getRecordType() {
        return MemberVotedQuestionRecord.class;
    }

    /**
     * The column <code>public.member_voted_question.account_id</code>.
     */
    public static final TableField<MemberVotedQuestionRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEMBER_VOTED_QUESTION_TABLE, "");

    /**
     * The column <code>public.member_voted_question.question_id</code>.
     */
    public static final TableField<MemberVotedQuestionRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), MEMBER_VOTED_QUESTION_TABLE, "");

    /**
     * The column <code>public.member_voted_question.upvoted</code>.
     */
    public static final TableField<MemberVotedQuestionRecord, Boolean> UPVOTED = createField(DSL.name("upvoted"), org.jooq.impl.SQLDataType.BOOLEAN, MEMBER_VOTED_QUESTION_TABLE, "");

    /**
     * No further instances allowed
     */
    private MemberVotedQuestionTable() {
        this(DSL.name("member_voted_question"), null);
    }

    private MemberVotedQuestionTable(Name alias, Table<MemberVotedQuestionRecord> aliased) {
        this(alias, aliased, null);
    }

    private MemberVotedQuestionTable(Name alias, Table<MemberVotedQuestionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MemberVotedQuestionTable(Table<O> child, ForeignKey<O, MemberVotedQuestionRecord> key) {
        super(child, key, MEMBER_VOTED_QUESTION_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEMBER_VOTED_QUESTION_PKEY);
    }

    @Override
    public UniqueKey<MemberVotedQuestionRecord> getPrimaryKey() {
        return Keys.MEMBER_VOTED_QUESTION_PKEY;
    }

    @Override
    public List<UniqueKey<MemberVotedQuestionRecord>> getKeys() {
        return Arrays.<UniqueKey<MemberVotedQuestionRecord>>asList(Keys.MEMBER_VOTED_QUESTION_PKEY);
    }

    @Override
    public List<ForeignKey<MemberVotedQuestionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MemberVotedQuestionRecord, ?>>asList(Keys.MEMBER_VOTED_QUESTION__FK_ACCOUNT_VOTED_QUESTION_ACCOUNT_ID, Keys.MEMBER_VOTED_QUESTION__FK_ACCOUNT_VOTED_QUESTION_QUESTION_ID);
    }

    public AccountTable account() {
        return new AccountTable(this, Keys.MEMBER_VOTED_QUESTION__FK_ACCOUNT_VOTED_QUESTION_ACCOUNT_ID);
    }

    public QuestionTable question() {
        return new QuestionTable(this, Keys.MEMBER_VOTED_QUESTION__FK_ACCOUNT_VOTED_QUESTION_QUESTION_ID);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
