/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Indexes;
import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.PhotoRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhotoTable extends TableImpl<PhotoRecord> {

    private static final long serialVersionUID = 750775289;

    /**
     * The reference instance of <code>public.photo</code>
     */
    public static final PhotoTable PHOTO_TABLE = new PhotoTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhotoRecord> getRecordType() {
        return PhotoRecord.class;
    }

    /**
     * The column <code>public.photo.id</code>.
     */
    public static final TableField<PhotoRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('photo_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), PHOTO_TABLE, "");

    /**
     * The column <code>public.photo.photo_path</code>.
     */
    public static final TableField<PhotoRecord, String> PHOTO_PATH = createField(DSL.name("photo_path"), org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), PHOTO_TABLE, "");

    /**
     * The column <code>public.photo.creation_date</code>.
     */
    public static final TableField<PhotoRecord, Timestamp> CREATION_DATE = createField(DSL.name("creation_date"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), PHOTO_TABLE, "");

    /**
     * The column <code>public.photo.question_id</code>.
     */
    public static final TableField<PhotoRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), org.jooq.impl.SQLDataType.BIGINT, PHOTO_TABLE, "");

    /**
     * The column <code>public.photo.answer_id</code>.
     */
    public static final TableField<PhotoRecord, Long> ANSWER_ID = createField(DSL.name("answer_id"), org.jooq.impl.SQLDataType.BIGINT, PHOTO_TABLE, "");

    /**
     * No further instances allowed
     */
    private PhotoTable() {
        this(DSL.name("photo"), null);
    }

    private PhotoTable(Name alias, Table<PhotoRecord> aliased) {
        this(alias, aliased, null);
    }

    private PhotoTable(Name alias, Table<PhotoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PhotoTable(Table<O> child, ForeignKey<O, PhotoRecord> key) {
        super(child, key, PHOTO_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PHOTO_PKEY);
    }

    @Override
    public Identity<PhotoRecord, Long> getIdentity() {
        return Keys.IDENTITY_PHOTO;
    }

    @Override
    public UniqueKey<PhotoRecord> getPrimaryKey() {
        return Keys.PHOTO_PKEY;
    }

    @Override
    public List<UniqueKey<PhotoRecord>> getKeys() {
        return Arrays.<UniqueKey<PhotoRecord>>asList(Keys.PHOTO_PKEY);
    }

    @Override
    public List<ForeignKey<PhotoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PhotoRecord, ?>>asList(Keys.PHOTO__FK_PHOTO_QUESTION_ID, Keys.PHOTO__FK_PHOTO_ANSWER_ID);
    }

    public QuestionTable question() {
        return new QuestionTable(this, Keys.PHOTO__FK_PHOTO_QUESTION_ID);
    }

    public AnswerTable answer() {
        return new AnswerTable(this, Keys.PHOTO__FK_PHOTO_ANSWER_ID);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Timestamp, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
