/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.QuestionClosingRemarkRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionClosingRemarkTable extends TableImpl<QuestionClosingRemarkRecord> {

    private static final long serialVersionUID = -802208478;

    /**
     * The reference instance of <code>public.question_closing_remark</code>
     */
    public static final QuestionClosingRemarkTable QUESTION_CLOSING_REMARK_TABLE = new QuestionClosingRemarkTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestionClosingRemarkRecord> getRecordType() {
        return QuestionClosingRemarkRecord.class;
    }

    /**
     * The column <code>public.question_closing_remark.id</code>.
     */
    public final TableField<QuestionClosingRemarkRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('question_closing_remark_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.question_closing_remark.remark</code>.
     */
    public final TableField<QuestionClosingRemarkRecord, String> REMARK = createField(DSL.name("remark"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * Create a <code>public.question_closing_remark</code> table reference
     */
    public QuestionClosingRemarkTable() {
        this(DSL.name("question_closing_remark"), null);
    }

    /**
     * Create an aliased <code>public.question_closing_remark</code> table reference
     */
    public QuestionClosingRemarkTable(String alias) {
        this(DSL.name(alias), QUESTION_CLOSING_REMARK_TABLE);
    }

    /**
     * Create an aliased <code>public.question_closing_remark</code> table reference
     */
    public QuestionClosingRemarkTable(Name alias) {
        this(alias, QUESTION_CLOSING_REMARK_TABLE);
    }

    private QuestionClosingRemarkTable(Name alias, Table<QuestionClosingRemarkRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuestionClosingRemarkTable(Name alias, Table<QuestionClosingRemarkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> QuestionClosingRemarkTable(Table<O> child, ForeignKey<O, QuestionClosingRemarkRecord> key) {
        super(child, key, QUESTION_CLOSING_REMARK_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<QuestionClosingRemarkRecord, Long> getIdentity() {
        return Keys.IDENTITY_QUESTION_CLOSING_REMARK;
    }

    @Override
    public UniqueKey<QuestionClosingRemarkRecord> getPrimaryKey() {
        return Keys.QUESTION_CLOSING_REMARK_PKEY;
    }

    @Override
    public List<UniqueKey<QuestionClosingRemarkRecord>> getKeys() {
        return Arrays.<UniqueKey<QuestionClosingRemarkRecord>>asList(Keys.QUESTION_CLOSING_REMARK_PKEY);
    }

    @Override
    public QuestionClosingRemarkTable as(String alias) {
        return new QuestionClosingRemarkTable(DSL.name(alias), this);
    }

    @Override
    public QuestionClosingRemarkTable as(Name alias) {
        return new QuestionClosingRemarkTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestionClosingRemarkTable rename(String name) {
        return new QuestionClosingRemarkTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestionClosingRemarkTable rename(Name name) {
        return new QuestionClosingRemarkTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
