/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.TagQuestionRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagQuestionTable extends TableImpl<TagQuestionRecord> {

    private static final long serialVersionUID = -1865413301;

    /**
     * The reference instance of <code>public.tag_question</code>
     */
    public static final TagQuestionTable TAG_QUESTION_TABLE = new TagQuestionTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagQuestionRecord> getRecordType() {
        return TagQuestionRecord.class;
    }

    /**
     * The column <code>public.tag_question.tag_id</code>.
     */
    public static final TableField<TagQuestionRecord, Long> TAG_ID = createField(DSL.name("tag_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), TAG_QUESTION_TABLE, "");

    /**
     * The column <code>public.tag_question.question_id</code>.
     */
    public static final TableField<TagQuestionRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), TAG_QUESTION_TABLE, "");

    /**
     * No further instances allowed
     */
    private TagQuestionTable() {
        this(DSL.name("tag_question"), null);
    }

    private TagQuestionTable(Name alias, Table<TagQuestionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagQuestionTable(Name alias, Table<TagQuestionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TagQuestionTable(Table<O> child, ForeignKey<O, TagQuestionRecord> key) {
        super(child, key, TAG_QUESTION_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<TagQuestionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TagQuestionRecord, ?>>asList(Keys.TAG_QUESTION__FK_TAG_QUESTION_TAG_ID, Keys.TAG_QUESTION__FK_TAG_QUESTION_QUESTION_ID);
    }

    public TagTable tag() {
        return new TagTable(this, Keys.TAG_QUESTION__FK_TAG_QUESTION_TAG_ID);
    }

    public QuestionTable question() {
        return new QuestionTable(this, Keys.TAG_QUESTION__FK_TAG_QUESTION_QUESTION_ID);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
