/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables;


import com.ra.course.com.stackoverflow.entity.jooq.Keys;
import com.ra.course.com.stackoverflow.entity.jooq.Public;
import com.ra.course.com.stackoverflow.entity.jooq.tables.records.TagRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTable extends TableImpl<TagRecord> {

    private static final long serialVersionUID = 1780525118;

    /**
     * The reference instance of <code>public.tag</code>
     */
    public static final TagTable TAG_TABLE = new TagTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagRecord> getRecordType() {
        return TagRecord.class;
    }

    /**
     * The column <code>public.tag.id</code>.
     */
    public final TableField<TagRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('tag_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.tag.name</code>.
     */
    public final TableField<TagRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.tag.description</code>.
     */
    public final TableField<TagRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.tag</code> table reference
     */
    public TagTable() {
        this(DSL.name("tag"), null);
    }

    /**
     * Create an aliased <code>public.tag</code> table reference
     */
    public TagTable(String alias) {
        this(DSL.name(alias), TAG_TABLE);
    }

    /**
     * Create an aliased <code>public.tag</code> table reference
     */
    public TagTable(Name alias) {
        this(alias, TAG_TABLE);
    }

    private TagTable(Name alias, Table<TagRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagTable(Name alias, Table<TagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TagTable(Table<O> child, ForeignKey<O, TagRecord> key) {
        super(child, key, TAG_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<TagRecord, Long> getIdentity() {
        return Keys.IDENTITY_TAG;
    }

    @Override
    public UniqueKey<TagRecord> getPrimaryKey() {
        return Keys.TAG_PKEY;
    }

    @Override
    public List<UniqueKey<TagRecord>> getKeys() {
        return Arrays.<UniqueKey<TagRecord>>asList(Keys.TAG_PKEY);
    }

    @Override
    public TagTable as(String alias) {
        return new TagTable(DSL.name(alias), this);
    }

    @Override
    public TagTable as(Name alias) {
        return new TagTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTable rename(String name) {
        return new TagTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTable rename(Name name) {
        return new TagTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
