/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables.records;


import com.ra.course.com.stackoverflow.entity.jooq.tables.AccountTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> implements Record6<Long, String, String, String, Integer, Long> {

    private static final long serialVersionUID = 796211830;

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account.password</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.password</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.account.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.account.reputation</code>.
     */
    public void setReputation(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account.reputation</code>.
     */
    public Integer getReputation() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.account.account_status_id</code>.
     */
    public void setAccountStatusId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account.account_status_id</code>.
     */
    public Long getAccountStatusId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Integer, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, Integer, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AccountTable.ACCOUNT_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return AccountTable.ACCOUNT_TABLE.PASSWORD;
    }

    @Override
    public Field<String> field3() {
        return AccountTable.ACCOUNT_TABLE.NAME;
    }

    @Override
    public Field<String> field4() {
        return AccountTable.ACCOUNT_TABLE.EMAIL;
    }

    @Override
    public Field<Integer> field5() {
        return AccountTable.ACCOUNT_TABLE.REPUTATION;
    }

    @Override
    public Field<Long> field6() {
        return AccountTable.ACCOUNT_TABLE.ACCOUNT_STATUS_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPassword();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public Integer component5() {
        return getReputation();
    }

    @Override
    public Long component6() {
        return getAccountStatusId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPassword();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public Integer value5() {
        return getReputation();
    }

    @Override
    public Long value6() {
        return getAccountStatusId();
    }

    @Override
    public AccountRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AccountRecord value2(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AccountRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AccountRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AccountRecord value5(Integer value) {
        setReputation(value);
        return this;
    }

    @Override
    public AccountRecord value6(Long value) {
        setAccountStatusId(value);
        return this;
    }

    @Override
    public AccountRecord values(Long value1, String value2, String value3, String value4, Integer value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(AccountTable.ACCOUNT_TABLE);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Long id, String password, String name, String email, Integer reputation, Long accountStatusId) {
        super(AccountTable.ACCOUNT_TABLE);

        set(0, id);
        set(1, password);
        set(2, name);
        set(3, email);
        set(4, reputation);
        set(5, accountStatusId);
    }
}
