/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables.records;


import com.ra.course.com.stackoverflow.entity.jooq.tables.AccountStatusTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountStatusRecord extends UpdatableRecordImpl<AccountStatusRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 295439082;

    /**
     * Setter for <code>public.account_status.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account_status.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account_status.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account_status.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AccountStatusTable.ACCOUNT_STATUS_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return AccountStatusTable.ACCOUNT_STATUS_TABLE.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStatus();
    }

    @Override
    public AccountStatusRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AccountStatusRecord value2(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public AccountStatusRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountStatusRecord
     */
    public AccountStatusRecord() {
        super(AccountStatusTable.ACCOUNT_STATUS_TABLE);
    }

    /**
     * Create a detached, initialised AccountStatusRecord
     */
    public AccountStatusRecord(Long id, String status) {
        super(AccountStatusTable.ACCOUNT_STATUS_TABLE);

        set(0, id);
        set(1, status);
    }
}
