/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables.records;


import com.ra.course.com.stackoverflow.entity.jooq.enums.BadgeType;
import com.ra.course.com.stackoverflow.entity.jooq.tables.MemberBadgeQuestionTable;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberBadgeQuestionRecord extends UpdatableRecordImpl<MemberBadgeQuestionRecord> implements Record3<Long, BadgeType, Long> {

    private static final long serialVersionUID = -1523455686;

    /**
     * Setter for <code>public.member_badge_question.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.member_badge_question.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.member_badge_question.badge</code>.
     */
    public void setBadge(BadgeType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.member_badge_question.badge</code>.
     */
    public BadgeType getBadge() {
        return (BadgeType) get(1);
    }

    /**
     * Setter for <code>public.member_badge_question.question_id</code>.
     */
    public void setQuestionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.member_badge_question.question_id</code>.
     */
    public Long getQuestionId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, BadgeType, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, BadgeType, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, BadgeType, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MemberBadgeQuestionTable.ACCOUNT_ID;
    }

    @Override
    public Field<BadgeType> field2() {
        return MemberBadgeQuestionTable.BADGE;
    }

    @Override
    public Field<Long> field3() {
        return MemberBadgeQuestionTable.QUESTION_ID;
    }

    @Override
    public Long component1() {
        return getAccountId();
    }

    @Override
    public BadgeType component2() {
        return getBadge();
    }

    @Override
    public Long component3() {
        return getQuestionId();
    }

    @Override
    public Long value1() {
        return getAccountId();
    }

    @Override
    public BadgeType value2() {
        return getBadge();
    }

    @Override
    public Long value3() {
        return getQuestionId();
    }

    @Override
    public MemberBadgeQuestionRecord value1(Long value) {
        setAccountId(value);
        return this;
    }

    @Override
    public MemberBadgeQuestionRecord value2(BadgeType value) {
        setBadge(value);
        return this;
    }

    @Override
    public MemberBadgeQuestionRecord value3(Long value) {
        setQuestionId(value);
        return this;
    }

    @Override
    public MemberBadgeQuestionRecord values(Long value1, BadgeType value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberBadgeQuestionRecord
     */
    public MemberBadgeQuestionRecord() {
        super(MemberBadgeQuestionTable.MEMBER_BADGE_QUESTION_TABLE);
    }

    /**
     * Create a detached, initialised MemberBadgeQuestionRecord
     */
    public MemberBadgeQuestionRecord(Long accountId, BadgeType badge, Long questionId) {
        super(MemberBadgeQuestionTable.MEMBER_BADGE_QUESTION_TABLE);

        set(0, accountId);
        set(1, badge);
        set(2, questionId);
    }
}
