/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq.tables.records;


import com.ra.course.com.stackoverflow.entity.jooq.tables.QuestionTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionRecord extends UpdatableRecordImpl<QuestionRecord> implements Record11<Long, String, String, Integer, Integer, LocalDateTime, LocalDateTime, Long, Long, Long, Long> {

    private static final long serialVersionUID = 22544838;

    /**
     * Setter for <code>public.question.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.question.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.question.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.question.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.question.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.question.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.question.view_count</code>.
     */
    public void setViewCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.question.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.question.vote_count</code>.
     */
    public void setVoteCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.question.vote_count</code>.
     */
    public Integer getVoteCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.question.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.question.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.question.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.question.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.question.status_id</code>.
     */
    public void setStatusId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.question.status_id</code>.
     */
    public Long getStatusId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.question.closing_remark_id</code>.
     */
    public void setClosingRemarkId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.question.closing_remark_id</code>.
     */
    public Long getClosingRemarkId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.question.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.question.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.question.bounty_id</code>.
     */
    public void setBountyId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.question.bounty_id</code>.
     */
    public Long getBountyId() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, Integer, Integer, LocalDateTime, LocalDateTime, Long, Long, Long, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, Integer, Integer, LocalDateTime, LocalDateTime, Long, Long, Long, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QuestionTable.QUESTION_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return QuestionTable.QUESTION_TABLE.TITLE;
    }

    @Override
    public Field<String> field3() {
        return QuestionTable.QUESTION_TABLE.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return QuestionTable.QUESTION_TABLE.VIEW_COUNT;
    }

    @Override
    public Field<Integer> field5() {
        return QuestionTable.QUESTION_TABLE.VOTE_COUNT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return QuestionTable.QUESTION_TABLE.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return QuestionTable.QUESTION_TABLE.UPDATE_TIME;
    }

    @Override
    public Field<Long> field8() {
        return QuestionTable.QUESTION_TABLE.STATUS_ID;
    }

    @Override
    public Field<Long> field9() {
        return QuestionTable.QUESTION_TABLE.CLOSING_REMARK_ID;
    }

    @Override
    public Field<Long> field10() {
        return QuestionTable.QUESTION_TABLE.AUTHOR_ID;
    }

    @Override
    public Field<Long> field11() {
        return QuestionTable.QUESTION_TABLE.BOUNTY_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getViewCount();
    }

    @Override
    public Integer component5() {
        return getVoteCount();
    }

    @Override
    public LocalDateTime component6() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateTime();
    }

    @Override
    public Long component8() {
        return getStatusId();
    }

    @Override
    public Long component9() {
        return getClosingRemarkId();
    }

    @Override
    public Long component10() {
        return getAuthorId();
    }

    @Override
    public Long component11() {
        return getBountyId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getViewCount();
    }

    @Override
    public Integer value5() {
        return getVoteCount();
    }

    @Override
    public LocalDateTime value6() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateTime();
    }

    @Override
    public Long value8() {
        return getStatusId();
    }

    @Override
    public Long value9() {
        return getClosingRemarkId();
    }

    @Override
    public Long value10() {
        return getAuthorId();
    }

    @Override
    public Long value11() {
        return getBountyId();
    }

    @Override
    public QuestionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QuestionRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public QuestionRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public QuestionRecord value4(Integer value) {
        setViewCount(value);
        return this;
    }

    @Override
    public QuestionRecord value5(Integer value) {
        setVoteCount(value);
        return this;
    }

    @Override
    public QuestionRecord value6(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public QuestionRecord value7(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public QuestionRecord value8(Long value) {
        setStatusId(value);
        return this;
    }

    @Override
    public QuestionRecord value9(Long value) {
        setClosingRemarkId(value);
        return this;
    }

    @Override
    public QuestionRecord value10(Long value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public QuestionRecord value11(Long value) {
        setBountyId(value);
        return this;
    }

    @Override
    public QuestionRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, LocalDateTime value6, LocalDateTime value7, Long value8, Long value9, Long value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestionRecord
     */
    public QuestionRecord() {
        super(QuestionTable.QUESTION_TABLE);
    }

    /**
     * Create a detached, initialised QuestionRecord
     */
    public QuestionRecord(Long id, String title, String description, Integer viewCount, Integer voteCount, LocalDateTime creationTime, LocalDateTime updateTime, Long statusId, Long closingRemarkId, Long authorId, Long bountyId) {
        super(QuestionTable.QUESTION_TABLE);

        set(0, id);
        set(1, title);
        set(2, description);
        set(3, viewCount);
        set(4, voteCount);
        set(5, creationTime);
        set(6, updateTime);
        set(7, statusId);
        set(8, closingRemarkId);
        set(9, authorId);
        set(10, bountyId);
    }
}
