/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq;


import com.ra.course.com.stackoverflow.entity.jooq.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PKEY = Indexes0.ACCOUNT_PKEY;
    public static final Index ANSWER_PKEY = Indexes0.ANSWER_PKEY;
    public static final Index BOUNTY_PKEY = Indexes0.BOUNTY_PKEY;
    public static final Index COMMENT_PKEY = Indexes0.COMMENT_PKEY;
    public static final Index MEMBER_PKEY = Indexes0.MEMBER_PKEY;
    public static final Index NOTIFICATION_PKEY = Indexes0.NOTIFICATION_PKEY;
    public static final Index PHOTO_PKEY = Indexes0.PHOTO_PKEY;
    public static final Index QUESTION_PKEY = Indexes0.QUESTION_PKEY;
    public static final Index TAG_PKEY = Indexes0.TAG_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PKEY = Internal.createIndex("account_pkey", AccountTable.ACCOUNT_TABLE, new OrderField[] { AccountTable.ID }, true);
        public static Index ANSWER_PKEY = Internal.createIndex("answer_pkey", AnswerTable.ANSWER_TABLE, new OrderField[] { AnswerTable.ID }, true);
        public static Index BOUNTY_PKEY = Internal.createIndex("bounty_pkey", BountyTable.BOUNTY_TABLE, new OrderField[] { BountyTable.ID }, true);
        public static Index COMMENT_PKEY = Internal.createIndex("comment_pkey", CommentTable.COMMENT_TABLE, new OrderField[] { CommentTable.ID }, true);
        public static Index MEMBER_PKEY = Internal.createIndex("member_pkey", MemberTable.MEMBER_TABLE, new OrderField[] { MemberTable.ID }, true);
        public static Index NOTIFICATION_PKEY = Internal.createIndex("notification_pkey", NotificationTable.NOTIFICATION_TABLE, new OrderField[] { NotificationTable.ID }, true);
        public static Index PHOTO_PKEY = Internal.createIndex("photo_pkey", PhotoTable.PHOTO_TABLE, new OrderField[] { PhotoTable.ID }, true);
        public static Index QUESTION_PKEY = Internal.createIndex("question_pkey", QuestionTable.QUESTION_TABLE, new OrderField[] { QuestionTable.ID }, true);
        public static Index TAG_PKEY = Internal.createIndex("tag_pkey", TagTable.TAG_TABLE, new OrderField[] { TagTable.ID }, true);
    }
}
