/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq;


import com.ra.course.com.stackoverflow.entity.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1768721091;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final AccountTable ACCOUNT = AccountTable.ACCOUNT_TABLE;

    /**
     * The table <code>public.account_status</code>.
     */
    public final AccountStatusTable ACCOUNT_STATUS = AccountStatusTable.ACCOUNT_STATUS_TABLE;

    /**
     * The table <code>public.answer</code>.
     */
    public final AnswerTable ANSWER = AnswerTable.ANSWER_TABLE;

    /**
     * The table <code>public.bounty</code>.
     */
    public final BountyTable BOUNTY = BountyTable.BOUNTY_TABLE;

    /**
     * The table <code>public.comment</code>.
     */
    public final CommentTable COMMENT = CommentTable.COMMENT_TABLE;

    /**
     * The table <code>public.member</code>.
     */
    public final MemberTable MEMBER = MemberTable.MEMBER_TABLE;

    /**
     * The table <code>public.photo</code>.
     */
    public final PhotoTable PHOTO = PhotoTable.PHOTO_TABLE;

    /**
     * The table <code>public.question</code>.
     */
    public final QuestionTable QUESTION = QuestionTable.QUESTION_TABLE;

    /**
     * The table <code>public.question_closing_remark</code>.
     */
    public final QuestionClosingRemarkTable QUESTION_CLOSING_REMARK = QuestionClosingRemarkTable.QUESTION_CLOSING_REMARK_TABLE;

    /**
     * The table <code>public.question_status</code>.
     */
    public final QuestionStatusTable QUESTION_STATUS = QuestionStatusTable.QUESTION_STATUS_TABLE;

    /**
     * The table <code>public.tag</code>.
     */
    public final TagTable TAG = TagTable.TAG_TABLE;

    /**
     * The table <code>public.tag_question</code>.
     */
    public final TagQuestionTable TAG_QUESTION = TagQuestionTable.TAG_QUESTION_TABLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACCOUNT_ID_SEQ,
            Sequences.ACCOUNT_STATUS_ID_SEQ,
            Sequences.ANSWER_ID_SEQ,
            Sequences.BOUNTY_ID_SEQ,
            Sequences.COMMENT_ID_SEQ,
            Sequences.MEMBER_ID_SEQ,
            Sequences.PHOTO_ID_SEQ,
            Sequences.QUESTION_CLOSING_REMARK_ID_SEQ,
            Sequences.QUESTION_ID_SEQ,
            Sequences.QUESTION_STATUS_ID_SEQ,
            Sequences.TAG_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AccountTable.ACCOUNT_TABLE,
            AccountStatusTable.ACCOUNT_STATUS_TABLE,
            AnswerTable.ANSWER_TABLE,
            BountyTable.BOUNTY_TABLE,
            CommentTable.COMMENT_TABLE,
            MemberTable.MEMBER_TABLE,
            PhotoTable.PHOTO_TABLE,
            QuestionTable.QUESTION_TABLE,
            QuestionClosingRemarkTable.QUESTION_CLOSING_REMARK_TABLE,
            QuestionStatusTable.QUESTION_STATUS_TABLE,
            TagTable.TAG_TABLE,
            TagQuestionTable.TAG_QUESTION_TABLE);
    }
}
