/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.account_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_ID_SEQ = new SequenceImpl<Long>("account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.answer_id_seq</code>
     */
    public static final Sequence<Long> ANSWER_ID_SEQ = new SequenceImpl<Long>("answer_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.bounty_id_seq</code>
     */
    public static final Sequence<Long> BOUNTY_ID_SEQ = new SequenceImpl<Long>("bounty_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.comment_id_seq</code>
     */
    public static final Sequence<Long> COMMENT_ID_SEQ = new SequenceImpl<Long>("comment_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.member_id_seq</code>
     */
    public static final Sequence<Long> MEMBER_ID_SEQ = new SequenceImpl<Long>("member_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.notification_id_seq</code>
     */
    public static final Sequence<Long> NOTIFICATION_ID_SEQ = new SequenceImpl<Long>("notification_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.photo_id_seq</code>
     */
    public static final Sequence<Long> PHOTO_ID_SEQ = new SequenceImpl<Long>("photo_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.question_id_seq</code>
     */
    public static final Sequence<Long> QUESTION_ID_SEQ = new SequenceImpl<Long>("question_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tag_id_seq</code>
     */
    public static final Sequence<Long> TAG_ID_SEQ = new SequenceImpl<Long>("tag_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
