/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import static org.jooq.impl.SQLDataType.BIGINT;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.account_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_ID_SEQ = Internal.createSequence("account_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.account_status_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_STATUS_ID_SEQ = Internal.createSequence("account_status_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.answer_id_seq</code>
     */
    public static final Sequence<Long> ANSWER_ID_SEQ = Internal.createSequence("answer_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.bounty_id_seq</code>
     */
    public static final Sequence<Long> BOUNTY_ID_SEQ = Internal.createSequence("bounty_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.comment_id_seq</code>
     */
    public static final Sequence<Long> COMMENT_ID_SEQ = Internal.createSequence("comment_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.member_id_seq</code>
     */
    public static final Sequence<Long> MEMBER_ID_SEQ = Internal.createSequence("member_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.photo_id_seq</code>
     */
    public static final Sequence<Long> PHOTO_ID_SEQ = Internal.createSequence("photo_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.question_closing_remark_id_seq</code>
     */
    public static final Sequence<Long> QUESTION_CLOSING_REMARK_ID_SEQ = Internal.createSequence("question_closing_remark_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.question_id_seq</code>
     */
    public static final Sequence<Long> QUESTION_ID_SEQ = Internal.createSequence("question_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.question_status_id_seq</code>
     */
    public static final Sequence<Long> QUESTION_STATUS_ID_SEQ = Internal.createSequence("question_status_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.tag_id_seq</code>
     */
    public static final Sequence<Long> TAG_ID_SEQ = Internal.createSequence("tag_id_seq", Public.PUBLIC, BIGINT.nullable(false), null, null, null, null, false, null);
}
