/*
 * This file is generated by jOOQ.
 */
package com.ra.course.com.stackoverflow.entity.jooq;


import com.ra.course.com.stackoverflow.entity.jooq.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final AccountTable ACCOUNT_TABLE = AccountTable.ACCOUNT_TABLE;

    /**
     * The table <code>public.answer</code>.
     */
    public static final AnswerTable ANSWER_TABLE = AnswerTable.ANSWER_TABLE;

    /**
     * The table <code>public.bounty</code>.
     */
    public static final BountyTable BOUNTY_TABLE = BountyTable.BOUNTY_TABLE;

    /**
     * The table <code>public.comment</code>.
     */
    public static final CommentTable COMMENT_TABLE = CommentTable.COMMENT_TABLE;

    /**
     * The table <code>public.member</code>.
     */
    public static final MemberTable MEMBER_TABLE = MemberTable.MEMBER_TABLE;

    /**
     * The table <code>public.notification</code>.
     */
    public static final NotificationTable NOTIFICATION_TABLE = NotificationTable.NOTIFICATION_TABLE;

    /**
     * The table <code>public.photo</code>.
     */
    public static final PhotoTable PHOTO_TABLE = PhotoTable.PHOTO_TABLE;

    /**
     * The table <code>public.question</code>.
     */
    public static final QuestionTable QUESTION_TABLE = QuestionTable.QUESTION_TABLE;

    /**
     * The table <code>public.tag</code>.
     */
    public static final TagTable TAG_TABLE = TagTable.TAG_TABLE;

    /**
     * The table <code>public.tag_question</code>.
     */
    public static final TagQuestionTable TAG_QUESTION_TABLE = TagQuestionTable.TAG_QUESTION_TABLE;
}
